// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/xissy/kubeflake (interfaces: IDGenerator)

// Package kubeflake is a generated GoMock package.
package kubeflake

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockIDGenerator is a mock of IDGenerator interface.
type MockIDGenerator struct {
	ctrl     *gomock.Controller
	recorder *MockIDGeneratorMockRecorder
}

// MockIDGeneratorMockRecorder is the mock recorder for MockIDGenerator.
type MockIDGeneratorMockRecorder struct {
	mock *MockIDGenerator
}

// NewMockIDGenerator creates a new mock instance.
func NewMockIDGenerator(ctrl *gomock.Controller) *MockIDGenerator {
	mock := &MockIDGenerator{ctrl: ctrl}
	mock.recorder = &MockIDGeneratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIDGenerator) EXPECT() *MockIDGeneratorMockRecorder {
	return m.recorder
}

// Must mocks base method.
func (m *MockIDGenerator) Must() uint64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Must")
	ret0, _ := ret[0].(uint64)
	return ret0
}

// Must indicates an expected call of Must.
func (mr *MockIDGeneratorMockRecorder) Must() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Must", reflect.TypeOf((*MockIDGenerator)(nil).Must))
}

// New mocks base method.
func (m *MockIDGenerator) New() (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "New")
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// New indicates an expected call of New.
func (mr *MockIDGeneratorMockRecorder) New() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "New", reflect.TypeOf((*MockIDGenerator)(nil).New))
}
